// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCREKHKjbvWl2IFtpfCvVXialX_lQktOMQ',
    appId: '1:626374799882:web:57d837b38a10e7008165f3',
    messagingSenderId: '626374799882',
    projectId: 'fir-test-98b9f',
    authDomain: 'fir-test-98b9f.firebaseapp.com',
    storageBucket: 'fir-test-98b9f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgAlBy3lD1b5XOtxX5QCF9ep0L8UFMpSI',
    appId: '1:626374799882:android:bebf1184d2fd16548165f3',
    messagingSenderId: '626374799882',
    projectId: 'fir-test-98b9f',
    storageBucket: 'fir-test-98b9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb6gxnNqSIo4ekw6MMHUnv_qVi188an-E',
    appId: '1:626374799882:ios:356d61fbaf3537288165f3',
    messagingSenderId: '626374799882',
    projectId: 'fir-test-98b9f',
    storageBucket: 'fir-test-98b9f.appspot.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb6gxnNqSIo4ekw6MMHUnv_qVi188an-E',
    appId: '1:626374799882:ios:06e561f4d484f0238165f3',
    messagingSenderId: '626374799882',
    projectId: 'fir-test-98b9f',
    storageBucket: 'fir-test-98b9f.appspot.com',
    iosBundleId: 'com.example.firebaseTest.RunnerTests',
  );
}
